import type { FinanceData } from "../types";

export const DEFAULT_FINANCE_DATA: FinanceData = {
  lastUpdated: new Date().toISOString(),
  assets: {
    emergencyCash: 150000,
    vaultLocation: "Kotak Savings Account",
    providentFund: 70000,
    uanNumber: "",
  },
  monthly: {
    income: 65000,
    fixedExpenses: 15000,
    variableExpenses: 8000,
    investments: 10000,
    momSupport: 15000,
    rentUtilities: 20000,
    lifestyleCap: 8000,
    emergencyTopUp: 5000,
    sipCapacity: 10000,
  },
  accounts: [
    {
      id: "1",
      type: "bank",
      name: "Primary Savings",
      institution: "Kotak Mahindra Bank",
      accountNumber: "****4521",
      currentValue: 150000,
      nominee: "Kalpana Ghodki (Mother)",
    },
    {
      id: "2",
      type: "epf",
      name: "Employee Provident Fund",
      institution: "EPFO",
      accountNumber: "UAN pending",
      currentValue: 70000,
      nominee: "Kalpana Ghodki (Mother)",
    },
  ],
  goals: [
    { id: "1", name: "Emergency Fund", target: 250000, current: 150000 },
    { id: "2", name: "Vacation", target: 100000, current: 25000 },
    { id: "3", name: "Car", target: 500000, current: 80000 },
    { id: "4", name: "House", target: 5000000, current: 200000 },
    { id: "5", name: "Retirement", target: 20000000, current: 70000 },
  ],
  insurance: [
    {
      id: "1",
      type: "term",
      name: "Term Life Cover (₹1 Crore Assurance)",
      policyNumber: "188144745",
      coverage: 10000000,
      renewalDate: "",
      nominee: "Kalpana Ghodki (Mother)",
    },
    {
      id: "2",
      type: "health",
      name: "Medical Shield Cover (₹10 Lakhs Cover)",
      policyNumber: "",
      coverage: 1000000,
      renewalDate: "2026-07-12",
      nominee: "",
    },
  ],
  documents: [],
  contacts: [
    { id: "1", role: "Trusted Family Successor", name: "Kalpana Ghodki (Mother)", contact: "" },
    { id: "2", role: "Chartered Accountant (Tax)", name: "", contact: "" },
    { id: "3", role: "Primary Bank Manager", name: "", contact: "" },
    { id: "4", role: "Insurance Advisor Node", name: "", contact: "" },
  ],
  instructions: {
    salaryAccount: "Kotak Savings Account",
    investmentLocations: "EPF via employer, SIPs via Groww",
    insuranceClaimSteps: "Contact insurer with policy number, submit death certificate and nominee ID",
    firstContact: "Kalpana Ghodki (Mother)",
    additionalNotes: "",
  },
  monthEndChecklist: {
    verifyBankLogs: false,
    confirmSipClearance: false,
    verifyBurnUnder30k: false,
    auditPolicyDates: false,
  },
  sosMode: false,
};
